# Generated by Django 2.2.24 on 2022-05-28 14:05

from django.db import migrations


NEW_BUILDING_YEAR = 2015


def fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        flat.new_building = flat.construction_year >= NEW_BUILDING_YEAR
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220528_1657'),
    ]

    operations = [
        migrations.RunPython(fill_new_building)
    ]



