# Generated by Django 2.2.24 on 2022-06-02 18:16

import phonenumbers
from django.db import migrations


COUNTRY_CODE = 'RU'


def full_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phonenumber = phonenumbers.parse(flat.owners_phonenumber, COUNTRY_CODE)
        if phonenumbers.is_valid_number(parsed_phonenumber):
            flat.owner_pure_phone = phonenumbers.format_number(
                parsed_phonenumber,
                phonenumbers.PhoneNumberFormat.INTERNATIONAL
            )
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(full_owner_pure_phone)
    ]
