# Generated by Django 2.2.24 on 2022-06-02 19:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owners_phonenumber',
        ),
        migrations.AddField(
            model_name='owner',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер владельца'),
        ),
        migrations.AddField(
            model_name='owner',
            name='pure_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
